/* Replace with your SQL commands */

CREATE TABLE property ( id INTEGER PRIMARY KEY ASC,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        last_listed_price DOUBLE,
                        appoximate_area_price DOUBLE,
                        residual_value DOUBLE DEFAULT 0,
                        last_listed_time TIMESTAMP,
                        last_updated_time TIMESTAMP,
                        mortgage DOUBLE,
                        taxes DOUBLE,
                        strda_fees DOUBLE,
                        year_built INTEGER,
                        tax_built INTEGER,
                        levels INTEGER,
                        bedrooms INTEGER,
                        size DOUBLE,
                        lot_size_sq_ft DOUBLE,
                        walkscore DOUBLE,
                        days_on_market DOUBLE,
                        type TEXT,
                        building_type TEXT,
                        ownership TEXT,
                        mls TEXT,
                        address TEXT,
                        info TEXT,
                        url TEXT,
                        source TEXT,
                        liked BOOLEAN DEFAULT FALSE,
                        removed BOOLEAN DEFAULT FALSE);
CREATE INDEX property_last_asked_price ON property(last_asked_price);
CREATE INDEX UNIQUE property_url ON property(url);
