/* Replace with your SQL commands */

CREATE TABLE property ( id INTEGER PRIMARY KEY ASC,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        last_listed_price DOUBLE,
                        appoximate_area_price DOUBLE,
                        residual_value DOUBLE DEFAULT 0,
                        last_listed_time TIMESTAMP,
                        last_updated_time TEXT,
                        mortgage DOUBLE,
                        taxes DOUBLE,
                        strata_fees DOUBLE,
                        year_built INTEGER,
                        levels INTEGER,
                        bedrooms INTEGER,
                        size DOUBLE,
                        lot_size_sq_ft DOUBLE,
                        walkscore DOUBLE,
                        days_on_market INTEGER,
                        type TEXT,
                        building_type TEXT,
                        ownership TEXT,
                        mls TEXT,
                        address TEXT,
                        info TEXT,
                        view TEXT,
                        url TEXT,
                        source TEXT,
                        currency TEXT,
                        country TEXT,
                        liked BOOLEAN DEFAULT FALSE,
                        removed BOOLEAN DEFAULT FALSE);
CREATE INDEX property_last_listed_price ON property(last_listed_price);
CREATE UNIQUE INDEX property_url ON property(url);
